### ISSUE TITLE
change repository name and related

### ISSUE THREAD

**Issue by jongmoon** [naver/egjs-transform#11]
## Description

This is jquery plugin. But User can't know that it is jquery plugin because current name(`egjs-transform`) does not expose it.

> It was needless to rename because egjs was developed using jquery. But Other egjs do not depend on jquery anymore.

New Name will be `egjs-jquery-transform`

**Comment by jongmoon** [comment]
## TODO

  - [x] CONTRIBUTING.md
  - [x] jsdoc.json
  - [x] NOTICE
  - [x] package.json
  - [x] README.md
  - [x] test/manual/index.html
  - [x] webpack.config.js
  - [x] demo
  - [x] repository name
  - [x] npm

## Issue

It is clear to change from `egjs-transform` to `egjs-jquery-transform`. But below cases are some ambiguous.

### jsdoc

| property | AS-IS | TO-BE |
|-----|-----|-----|
| applicationName | eg.Transform | ? |

**Candidates**
  - eg.$Transform (
  - eg.JQueryTransform
  - eg.Jquery.Transfrom
  - eg.jquery-transform
  - eg.jquery.transform

### package.json

| property | AS-IS | TO-BE |
|-----|-----|-----|
| name | \@ egjs/transform | ? |
| main | dist/transform.js | - (retain) |
| es2015 | src/Transform.js | -(retain) |

  - jquery-transform

Here we want to change repository. File names are not my concern. So retain file names.

### README.md

  - [x] Travis and coveralls are need to check!

### webpack.config.js

Retain entry name because entry name`transform` will be the file name.

```js
var config = {
   entry: {
     "transform": "./src/index.js"
  },
}
```
| property | AS-IS | TO-BE |
|-----|-----|-----|
| libarry | transform | - (retain) |

**Comment by jongmoon** [comment]
More Jobs Done
  - [x] travisCI
  - [x] coveralls
